apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
      - name: team-service
        image: bob/team-service:latest
        ports:
        - containerPort: 6650